import React, { useEffect, useState } from 'react';
import { LogOut, LayoutDashboard, User as UserIcon, ChevronRight, ChevronDown } from 'lucide-react';
import { signInWithPopup, onAuthStateChanged, signOut } from 'firebase/auth';
import { auth, googleProvider, isFirebaseConfigured } from '../services/firebase';

interface AuthButtonProps { onViewDashboard?: () => void; minimal?: boolean; }

export const AuthButton: React.FC<AuthButtonProps> = ({ onViewDashboard, minimal }) => {
  const [user, setUser] = useState<any>(null); const [loading, setLoading] = useState(false);
  useEffect(() => auth ? onAuthStateChanged(auth, async firebaseUser => { if (!firebaseUser) { setUser(null); localStorage.removeItem('project-finder-token'); localStorage.removeItem('project-finder-user'); return; } const token = await firebaseUser.getIdToken(); const data = { uid: firebaseUser.uid, displayName: firebaseUser.displayName, email: firebaseUser.email, photoURL: firebaseUser.photoURL, emailVerified: firebaseUser.emailVerified }; localStorage.setItem('project-finder-token', token); localStorage.setItem('project-finder-user', JSON.stringify(data)); setUser(data); window.dispatchEvent(new Event('storage')); }) : undefined, []);
  const login = async () => { if (window.location.hostname === '127.0.0.1') { window.location.href = window.location.href.replace('127.0.0.1', 'localhost'); return; } if (!auth || !isFirebaseConfigured) return alert('Google sign-in is not configured.'); setLoading(true); try { await signInWithPopup(auth, googleProvider); } catch (error: any) { const message = error?.code === 'auth/unauthorized-domain' ? `Google sign-in is blocked for ${window.location.hostname}. Add this domain in Firebase Console → Authentication → Settings → Authorized domains.` : (error.message || 'Google sign-in failed'); alert(message); } finally { setLoading(false); } };
  const logout = async () => { if (auth) await signOut(auth); localStorage.removeItem('project-finder-token'); localStorage.removeItem('project-finder-user'); localStorage.removeItem('project-finder-favorites'); setUser(null); window.dispatchEvent(new Event('storage')); };
  if (user) return minimal ? <button onClick={onViewDashboard} className="p-2.5 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-400"><UserIcon className="w-4 h-4" /></button> : <div className="relative"><button onClick={onViewDashboard} className="flex items-center gap-2 pl-1 md:pl-1.5 pr-3 md:pr-4 rounded-full hover:bg-white/5 text-white font-medium text-[10px] md:text-[11px] transition-all h-8 md:h-9"><img src={user.photoURL || `https://ui-avatars.com/api/?name=${user.displayName || user.email}`} className="w-6 h-6 md:w-7 md:h-7 rounded-full border border-orange-500/80 object-cover" alt="Profile" /><span className="hidden sm:inline-block tracking-wide uppercase">{user.displayName || 'Google User'}</span></button></div>;
  return <div className="relative"><div className="rounded-full bg-gradient-to-r from-orange-500/60 to-indigo-500/60 p-[1px] transition-all hover:shadow-[0_0_15px_rgba(139,92,246,0.3)] h-8 md:h-9 flex items-center"><button onClick={login} disabled={loading} className={minimal ? 'p-1.5 rounded-full bg-[#0f172a] w-full h-full disabled:opacity-50' : 'flex items-center gap-2 pl-1 md:pl-1.5 pr-3 md:pr-4 rounded-full bg-[#0f172a] hover:bg-[#131d30] text-white font-medium text-[10px] md:text-[11px] transition-all w-full h-full disabled:opacity-50'}><div className="bg-white/5 rounded-md md:rounded-xl shadow-sm flex items-center justify-center shrink-0 w-6 h-6 md:w-7 md:h-7"><svg className="w-3.5 h-3.5 md:w-4 md:h-4" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4"/><path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853"/><path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" fill="#FBBC05"/><path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335"/></svg></div><div className="w-px h-3 bg-white/10 hidden sm:block mx-0.5" />{!minimal && <span className="hidden sm:inline-block tracking-wide">{loading ? 'Connecting...' : 'Continue with Google'}</span>}<ChevronRight className="w-3 h-3 md:w-3.5 md:h-3.5 text-indigo-400 hidden sm:inline-block ml-0.5 md:ml-1" /></button></div></div>;
};
